language: python
python:
- '2.6'
- '2.7'
- '3.3'
- '3.4'
- pypy
deploy:
  provider: pypi
  user: davoclavo
  password:
    secure: WNU2dilyc7/QxnOeIR3bX1G8Q4BUdUwESa3GJWlnh9L0wDdzLSbVMn39EwAw7b7yPFJ5y3ZiqIgldt8Y/eaUbX9rBdax0xx+/gmrnv/9XoYp5eWCKYCoDvrDf2wz6ZKdeoVl56lpWyXVIklzdEnoh/D3i+GRIqRn3rwZb80e5F0=
install:
- python setup.py install
- pip install coveralls
script:
- python setup.py nosetests
after_success: coveralls
