language: python
python:
- '2.6'
- '2.7'
- '3.3'
- '3.4'
- pypy
deploy:
  provider: pypi
  user: davoclavo
  password:
    secure: nZV3cFcRVRgPhBO9LkBSpbSA0q/2YZZ+t774giYfK5cN1wrRqKXX0mqvuqOZTUS+MLYaQXGW22YByetIH83l+amWjd8uUxlo8P95xY+Ww9Wr34plLgW8w/YD1yNKnw3NyBrKIDQARoLLdAFpZO2MaRGWCIdNNPXAyh8VQ7tcJsw=
install:
- python setup.py install
- pip install coveralls
script:
- python setup.py nosetests
after_success: coveralls
